language: python
python:
    - "3.5"
os:
    - "linux"

install:
    - pip3 install coveralls
    - pip3 install coverage
    - pip3 install colored
script:
    - python3 -m unittest
    - python3 -m coverage run --omit test_rpn.py test_rpn.py
after_success:
    - coveralls
