language: python
python:
    - "3.5"
os:
    - "linux"

install:
    - pip install coveralls
    - pip install coverage
script:
    - python -m coverage run test_rpn.py
after_success:
    - coveralls
